#ifndef ERROS_H
#define ERROS_H

#define ESTAT_OK 0
#define ESTAT_ERRO_N_INVALIDO 1
#define ESTAT_ERRO_TAMANHOS_DIFERENTES 2
#define ESTAT_ERRO_DIVISAO_ZERO 3
#define ESTAT_ERRO_PARAMETRO_INVALIDO 4

#endif